export const BOOKMARK_SUCCESS = 'BOOKMARK_SUCCESS';
export const BOOKMARK_FAIL = 'BOOKMARK_FAIL';
export const UNBOOKMARK_SUCCESS = 'UNBOOKMARK_SUCCESS';
export const UNBOOKMARK_FAIL = 'UNBOOKMARK_FAIL';
export const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS';
export const GET_BOOKMARKS_FAIL = 'GET_BOOKMARKS_FAIL';
