export const CLEAR_FOLLOW = 'CLEAR_FOLLOW';
export const FOLLOW_AUTHOR_SUCCESS = 'FOLLOW_AUTHOR_SUCCES';
export const FOLLOW_AUTHOR_FAIL = 'FOLLOW_AUTHOR_FAIL';
export const UNFOLLOW_AUTHOR_SUCCESS = 'UNFOLLOW_AUTHOR_SUCCESS';
export const UNFOLLOW_AUTHOR_FAIL = 'UNFOLLOW_AUTHOR_FAIL';
export const GET_FOLLOWING_AUTHOR_SUCCESS = 'GET_FOLLOWING_AUTHOR_SUCCESS';
export const GET_FOLLOWING_AUTHOR_FAIL = 'GET_FOLLOWING_AUTHOR_FAIL';
